import type { BusinessIntelligenceSnapshot } from '../types/businessIntelligence'

export const businessIntelligenceSnapshot: BusinessIntelligenceSnapshot = {
  period: 'June 2026',
  generatedAt: '2026-06-12T08:30:00+08:00',
  kpis: [
    {
      label: 'Monthly Revenue',
      value: 'RM 128,640',
      change: '+14.8%',
      direction: 'up',
      context: 'RM 16,580 ahead of May',
    },
    {
      label: 'Gross Margin',
      value: '68.4%',
      change: '+2.1 pts',
      direction: 'up',
      context: 'Service mix improved',
    },
    {
      label: 'Customer Retention',
      value: '74%',
      change: '+5.6%',
      direction: 'up',
      context: '39 customers returned',
    },
    {
      label: 'Package Liability',
      value: 'RM 42,780',
      change: '-3.2%',
      direction: 'down',
      context: '186 sessions outstanding',
    },
    {
      label: 'Team Utilization',
      value: '78%',
      change: '+4.3 pts',
      direction: 'up',
      context: 'Peak hours at 91%',
    },
  ],
  health: {
    score: 86,
    status: 'Strong',
    change: 5,
    components: [
      { label: 'Revenue momentum', score: 92, change: 7 },
      { label: 'Customer health', score: 81, change: 4 },
      { label: 'Team capacity', score: 84, change: 3 },
      { label: 'Package exposure', score: 76, change: -2 },
      { label: 'Cash efficiency', score: 89, change: 6 },
    ],
  },
  revenueTrend: [
    { label: 'Jan', value: 86200, comparison: 79400 },
    { label: 'Feb', value: 91400, comparison: 83200 },
    { label: 'Mar', value: 98800, comparison: 90100 },
    { label: 'Apr', value: 107600, comparison: 96400 },
    { label: 'May', value: 112060, comparison: 103800 },
    { label: 'Jun', value: 128640, comparison: 109500, forecast: 132400 },
  ],
  therapists: [
    { id: 'TH-01', name: 'Nok S.', initials: 'NS', revenue: 31320, appointments: 94, utilization: 88, completionRate: 97, rebookingRate: 78, upsellRate: 32, rating: 4.9, revenueChange: 18, performanceScore: 91 },
    { id: 'TH-03', name: 'Mei L.', initials: 'ML', revenue: 28460, appointments: 82, utilization: 81, completionRate: 96, rebookingRate: 69, upsellRate: 41, rating: 4.9, revenueChange: 16, performanceScore: 88 },
    { id: 'TH-02', name: 'Aom M.', initials: 'AM', revenue: 27340, appointments: 86, utilization: 84, completionRate: 94, rebookingRate: 72, upsellRate: 28, rating: 4.8, revenueChange: 9, performanceScore: 85 },
    { id: 'TH-04', name: 'Pim J.', initials: 'PJ', revenue: 21480, appointments: 73, utilization: 72, completionRate: 92, rebookingRate: 64, upsellRate: 23, rating: 4.7, revenueChange: 6, performanceScore: 76 },
    { id: 'TH-05', name: 'Mali K.', initials: 'MK', revenue: 19640, appointments: 68, utilization: 69, completionRate: 95, rebookingRate: 67, upsellRate: 25, rating: 4.8, revenueChange: 11, performanceScore: 77 },
  ],
  atRiskCustomers: [
    { id: 'CUS-2045', name: 'Farah Rahman', membershipTier: 'Guest', daysInactive: 174, lifetimeValue: 840, riskScore: 94, reason: 'No visit after package expiry and two unanswered campaigns.', recommendedAction: 'Therapist-led personal recovery call with a shoulder-care offer.' },
    { id: 'CUS-2044', name: 'Michelle Goh', membershipTier: 'Silver', daysInactive: 120, lifetimeValue: 1440, riskScore: 88, reason: 'Missed latest appointment and membership renewal is overdue.', recommendedAction: 'Send a quiet-room recovery invitation and renewal benefit reminder.' },
    { id: 'CUS-2043', name: 'Daniel Wong', membershipTier: 'Guest', daysInactive: 54, lifetimeValue: 1920, riskScore: 73, reason: 'One package session remains and expires within 18 days.', recommendedAction: 'Reserve a Sunday recovery slot before package expiration.' },
    { id: 'CUS-2071', name: 'Jia Hui Tan', membershipTier: 'Gold', daysInactive: 47, lifetimeValue: 4860, riskScore: 68, reason: 'Visit frequency dropped from twice monthly to zero.', recommendedAction: 'Offer priority booking with her preferred therapist.' },
  ],
  customerSegments: [
    { label: 'VIP & Diamond', customers: 38, revenueShare: 34, color: 'gold' },
    { label: 'Active Members', customers: 148, revenueShare: 39, color: 'teal' },
    { label: 'Package Guests', customers: 96, revenueShare: 19, color: 'mint' },
    { label: 'At Risk / Lost', customers: 42, revenueShare: 8, color: 'sand' },
  ],
  packageLiabilities: [
    { id: 'PKD-02', name: 'Deep Restore 10', activePackages: 24, outstandingSessions: 82, liabilityValue: 21320, expiringWithin30Days: 7, redemptionRate: 72 },
    { id: 'PKD-03', name: 'Head Spa Ritual 6', activePackages: 31, outstandingSessions: 54, liabilityValue: 10638, expiringWithin30Days: 4, redemptionRate: 81 },
    { id: 'PKD-01', name: 'Sabai Reset 5', activePackages: 38, outstandingSessions: 36, liabilityValue: 7560, expiringWithin30Days: 3, redemptionRate: 88 },
    { id: 'PKD-04', name: 'Thai Wellness Journey', activePackages: 17, outstandingSessions: 14, liabilityValue: 3262, expiringWithin30Days: 2, redemptionRate: 79 },
  ],
  revenueForecast: [
    { month: 'Jan', actual: 86200, forecast: 84200, target: 90000 },
    { month: 'Feb', actual: 91400, forecast: 89500, target: 92000 },
    { month: 'Mar', actual: 98800, forecast: 97200, target: 98000 },
    { month: 'Apr', actual: 107600, forecast: 105400, target: 104000 },
    { month: 'May', actual: 112060, forecast: 111200, target: 110000 },
    { month: 'Jun', actual: 128640, forecast: 132400, target: 120000 },
    { month: 'Jul', forecast: 137800, target: 128000 },
    { month: 'Aug', forecast: 142600, target: 135000 },
    { month: 'Sep', forecast: 149200, target: 142000 },
  ],
  revenueMix: [
    { label: 'Services', amount: 89240, share: 69, change: 12.8 },
    { label: 'Packages', amount: 23800, share: 19, change: 18.4 },
    { label: 'Memberships', amount: 11240, share: 9, change: 9.2 },
    { label: 'Retail', amount: 4360, share: 3, change: -2.1 },
  ],
  aiInsights: [
    { id: 'AI-01', category: 'Growth', title: 'Extend premium head-spa capacity on Fridays', narrative: 'Friday head-spa utilization reached 96% for four consecutive weeks while 14 booking requests shifted to later dates.', impact: 'RM 8,400 estimated monthly upside', confidence: 92, priority: 'High', recommendedAction: 'Open two additional Mei L. slots and cross-train one therapist for scalp-care preparation.' },
    { id: 'AI-02', category: 'Retention', title: 'Recover high-value members before the 60-day mark', narrative: 'Nine Gold and Diamond members are approaching 60 days without a visit, representing RM 31,600 in historical annual value.', impact: 'RM 12,700 revenue at risk', confidence: 89, priority: 'High', recommendedAction: 'Launch therapist-personalized WhatsApp outreach within 48 hours.' },
    { id: 'AI-03', category: 'Risk', title: 'Reduce Deep Restore package liability', narrative: 'Deep Restore carries half of outstanding package liability and seven packages expire within 30 days.', impact: '82 sessions require capacity planning', confidence: 96, priority: 'High', recommendedAction: 'Reserve off-peak redemption blocks and notify package holders this week.' },
    { id: 'AI-04', category: 'Capacity', title: 'Pim J. has underused weekday capacity', narrative: 'Pim maintains a 4.7 rating but operates at 72% utilization, with the largest gaps on Tuesday and Thursday afternoons.', impact: 'RM 4,600 potential monthly revenue', confidence: 84, priority: 'Medium', recommendedAction: 'Route lymphatic recovery campaigns into Tuesday and Thursday availability.' },
  ],
  calculations: {
    customerMetrics: {
      vipCustomers: 38,
      activeCustomers: 148,
      atRiskCustomers: 24,
      lostCustomers: 18,
      birthdaysThisWeek: 6,
      inactiveOver30Days: 42,
      inactiveOver45Days: 31,
      inactiveOver60Days: 19,
    },
    packageMetrics: {
      activePackages: 110,
      outstandingSessions: 186,
      unusedPackageValue: 42780,
      expiringIn7Days: 3,
      expiringIn14Days: 7,
      expiringIn30Days: 16,
      redemptionRate: 80,
      liabilityWarning:
        'Deep Restore represents 49.8% of total package exposure.',
    },
    revenueByService: [
      { id: 'service-head-spa', label: 'Signature Head Spa', amount: 32600, appointments: 148 },
      { id: 'service-aromatherapy', label: 'Aromatherapy Massage', amount: 28400, appointments: 112 },
      { id: 'service-deep-tissue', label: 'Deep Tissue Massage', amount: 24900, appointments: 83 },
    ],
    revenueByTherapist: [
      { id: 'TH-01', label: 'Nok S.', amount: 31320, appointments: 94 },
      { id: 'TH-03', label: 'Mei L.', amount: 28460, appointments: 82 },
      { id: 'TH-02', label: 'Aom M.', amount: 27340, appointments: 86 },
    ],
    dailyRevenue: [
      { date: '2026-06-08', amount: 7820, visits: 25 },
      { date: '2026-06-09', amount: 8160, visits: 27 },
      { date: '2026-06-10', amount: 8420, visits: 28 },
    ],
    monthlyRevenue: 128640,
    averageRevenuePerVisit: 286,
    grossMarginPlaceholder: 68.4,
    notificationDeliveryRate: 96,
    openFollowUps: 18,
    completionEvents: 412,
  },
}
