import type { Appointment } from '../types/appointments'
import type {
  CommissionAdjustment,
  CommissionRule,
  CommissionStatement,
  TherapistCommission,
} from '../types/commissions'
import type { Customer } from '../types/customers'

export const appointments: Appointment[] = [
  {
    id: 'APT-1048',
    customer: 'Amelia Tan',
    phone: '+60 12-884 2108',
    service: 'Aromatherapy Massage',
    therapist: 'Nok S.',
    room: 'Lotus 2',
    date: '2026-06-10',
    time: '10:00',
    duration: 90,
    status: 'In Progress',
    price: 280,
    source: 'WhatsApp',
    notes: 'Prefers medium pressure and lavender oil.',
  },
  {
    id: 'APT-1049',
    customer: 'Sarah Lim',
    phone: '+60 17-620 4419',
    service: 'Signature Head Spa',
    therapist: 'Mei L.',
    room: 'Siam 1',
    date: '2026-06-10',
    time: '11:30',
    duration: 60,
    status: 'Checked In',
    price: 220,
    source: 'Online',
  },
  {
    id: 'APT-1050',
    customer: 'Daniel Wong',
    phone: '+60 16-311 7820',
    service: 'Deep Tissue Massage',
    therapist: 'Aom M.',
    room: 'Lotus 1',
    date: '2026-06-10',
    time: '12:00',
    duration: 90,
    status: 'Confirmed',
    price: 300,
    source: 'Referral',
  },
  {
    id: 'APT-1051',
    customer: 'Nur Aisyah',
    phone: '+60 19-522 8814',
    service: 'Thai Wellness Ritual',
    therapist: 'Nok S.',
    room: 'Siam 2',
    date: '2026-06-10',
    time: '13:30',
    duration: 120,
    status: 'Pending',
    price: 360,
    source: 'Walk-in',
  },
  {
    id: 'APT-1052',
    customer: 'Michelle Goh',
    phone: '+60 12-792 1033',
    service: 'Lymphatic Massage',
    therapist: 'Pim J.',
    room: 'Lotus 3',
    date: '2026-06-10',
    time: '15:00',
    duration: 60,
    status: 'No Show',
    price: 240,
    source: 'WhatsApp',
  },
  {
    id: 'APT-1047',
    customer: 'Farah Rahman',
    phone: '+60 11-340 7721',
    service: 'Aromatherapy Massage',
    therapist: 'Aom M.',
    room: 'Lotus 1',
    date: '2026-06-10',
    time: '09:00',
    duration: 60,
    status: 'Completed',
    price: 220,
    source: 'Online',
  },
]

export const customers: Customer[] = [
  {
    id: 'CUS-2041',
    name: 'Amelia Tan',
    phone: '+60 12-884 2108',
    email: 'amelia.tan@example.com',
    birthday: '1988-08-14',
    source: 'Instagram',
    lastVisit: '2026-06-10',
    preferredService: 'Aromatherapy Massage',
    lifetimeValue: 6840,
    packageBalance: 4,
    membershipTier: 'Signature',
    retentionStatus: 'VIP',
    nextAction: 'Offer priority renewal for Signature membership',
    wellnessSummary: 'Medium pressure, lavender oil, focus on shoulders. Avoid direct pressure on left knee.',
    followUpNotes: 'Appreciates evening appointments and therapist continuity.',
    visits: [
      { date: '2026-06-10', service: 'Aromatherapy Massage', therapist: 'Nok S.', amount: 280 },
      { date: '2026-05-18', service: 'Thai Wellness Ritual', therapist: 'Nok S.', amount: 360 },
      { date: '2026-04-22', service: 'Aromatherapy Massage', therapist: 'Nok S.', amount: 280 },
    ],
  },
  {
    id: 'CUS-2042',
    name: 'Sarah Lim',
    phone: '+60 17-620 4419',
    email: 'sarah.lim@example.com',
    birthday: '1992-02-03',
    source: 'Google',
    lastVisit: '2026-06-10',
    preferredService: 'Signature Head Spa',
    lifetimeValue: 2860,
    packageBalance: 2,
    membershipTier: 'Serenity',
    retentionStatus: 'Active',
    nextAction: 'Recommend Head Spa package after today’s visit',
    wellnessSummary: 'Sensitive scalp. Prefers low heat and fragrance-free products.',
    followUpNotes: 'Interested in monthly scalp-care routine.',
    visits: [
      { date: '2026-06-10', service: 'Signature Head Spa', therapist: 'Mei L.', amount: 220 },
      { date: '2026-05-07', service: 'Signature Head Spa', therapist: 'Mei L.', amount: 220 },
    ],
  },
  {
    id: 'CUS-2043',
    name: 'Daniel Wong',
    phone: '+60 16-311 7820',
    email: 'daniel.w@example.com',
    birthday: '1984-11-29',
    source: 'Referral',
    lastVisit: '2026-04-19',
    preferredService: 'Deep Tissue Massage',
    lifetimeValue: 1920,
    packageBalance: 1,
    membershipTier: 'None',
    retentionStatus: 'Follow Up Soon',
    nextAction: 'Rebook before final package session expires',
    wellnessSummary: 'Firm pressure. Lower back and hamstring focus after cycling.',
    followUpNotes: 'Usually books Sunday afternoon.',
    visits: [
      { date: '2026-04-19', service: 'Deep Tissue Massage', therapist: 'Aom M.', amount: 300 },
      { date: '2026-03-09', service: 'Deep Tissue Massage', therapist: 'Aom M.', amount: 300 },
    ],
  },
  {
    id: 'CUS-2044',
    name: 'Michelle Goh',
    phone: '+60 12-792 1033',
    email: 'michelle.goh@example.com',
    birthday: '1990-06-18',
    source: 'WhatsApp',
    lastVisit: '2026-02-12',
    preferredService: 'Lymphatic Massage',
    lifetimeValue: 1440,
    packageBalance: 0,
    membershipTier: 'Essential',
    retentionStatus: 'At Risk',
    nextAction: 'Send a personal recovery offer this week',
    wellnessSummary: 'Light pressure, quiet room, no strong essential oils.',
    followUpNotes: 'Missed latest appointment; check preferred contact time.',
    visits: [
      { date: '2026-02-12', service: 'Lymphatic Massage', therapist: 'Pim J.', amount: 240 },
    ],
  },
  {
    id: 'CUS-2045',
    name: 'Farah Rahman',
    phone: '+60 11-340 7721',
    email: 'farah.r@example.com',
    birthday: '1987-12-05',
    source: 'Walk-in',
    lastVisit: '2025-12-20',
    preferredService: 'Aromatherapy Massage',
    lifetimeValue: 840,
    packageBalance: 0,
    membershipTier: 'None',
    retentionStatus: 'Lost',
    nextAction: 'Invite back with a therapist-led wellness check-in',
    wellnessSummary: 'Medium pressure and citrus aromas. Shoulder tension.',
    followUpNotes: 'No response to last general promotion.',
    visits: [
      { date: '2025-12-20', service: 'Aromatherapy Massage', therapist: 'Aom M.', amount: 220 },
    ],
  },
]

export const therapistCommissions: TherapistCommission[] = [
  { id: 'TC-01', therapist: 'Nok S.', sessions: 94, serviceRevenue: 24480, packageSales: 5600, productSales: 1240, commission: 3820, bonus: 500, totalPayout: 4320, status: 'Approved' },
  { id: 'TC-02', therapist: 'Aom M.', sessions: 86, serviceRevenue: 22160, packageSales: 4200, productSales: 980, commission: 3380, bonus: 350, totalPayout: 3730, status: 'Pending' },
  { id: 'TC-03', therapist: 'Mei L.', sessions: 82, serviceRevenue: 19840, packageSales: 6800, productSales: 1820, commission: 3260, bonus: 420, totalPayout: 3680, status: 'Approved' },
  { id: 'TC-04', therapist: 'Pim J.', sessions: 73, serviceRevenue: 17620, packageSales: 3100, productSales: 760, commission: 2710, bonus: 200, totalPayout: 2910, status: 'Pending' },
]

export const commissionRules: CommissionRule[] = [
  { id: 'CR-01', name: 'Core Massage Services', appliesTo: 'Service', category: 'Massage', calculation: 'Percentage', rate: '12%', active: true, effectiveDate: '2026-01-01' },
  { id: 'CR-02', name: 'Premium Head Spa', appliesTo: 'Service', category: 'Head Spa', calculation: 'Tiered', rate: '10–15%', active: true, effectiveDate: '2026-03-01' },
  { id: 'CR-03', name: 'Wellness Package Sales', appliesTo: 'Package', category: 'All packages', calculation: 'Percentage', rate: '5%', active: true, effectiveDate: '2026-01-01' },
  { id: 'CR-04', name: 'Membership Activation', appliesTo: 'Membership', category: 'New memberships', calculation: 'Fixed', rate: 'RM 30', active: true, effectiveDate: '2026-04-01' },
]

export const commissionStatements: CommissionStatement[] = [
  { id: 'CS-01', therapist: 'Nok S.', period: 'June 2026', basicSalary: 2600, commission: 3820, bonus: 500, deductions: 0, netPayout: 6920, status: 'Approved' },
  { id: 'CS-02', therapist: 'Aom M.', period: 'June 2026', basicSalary: 2500, commission: 3380, bonus: 350, deductions: 120, netPayout: 6110, status: 'Pending Approval' },
  { id: 'CS-03', therapist: 'Mei L.', period: 'June 2026', basicSalary: 2500, commission: 3260, bonus: 420, deductions: 0, netPayout: 6180, status: 'Draft' },
  { id: 'CS-04', therapist: 'Pim J.', period: 'June 2026', basicSalary: 2400, commission: 2710, bonus: 200, deductions: 80, netPayout: 5230, status: 'Draft' },
]

export const commissionAdjustments: CommissionAdjustment[] = [
  { id: 'CA-01', therapist: 'Nok S.', reason: 'Monthly rebooking target', amount: 500, type: 'Bonus', approvedBy: 'Amelia Lee', date: '2026-06-05' },
  { id: 'CA-02', therapist: 'Aom M.', reason: 'Uniform replacement', amount: 120, type: 'Deduction', approvedBy: 'Amelia Lee', date: '2026-06-06' },
  { id: 'CA-03', therapist: 'Mei L.', reason: 'Head spa launch incentive', amount: 420, type: 'Bonus', approvedBy: 'Amelia Lee', date: '2026-06-07' },
  { id: 'CA-04', therapist: 'Pim J.', reason: 'Prior-period correction', amount: 80, type: 'Correction', approvedBy: 'Amelia Lee', date: '2026-06-08' },
]
